stuff:
  script:
    - echo we only deploy on commits to the prod branch


deploy:
  only:
    refs:
      - prod
  script:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} aws s3 cp s3://motuz-test/cicd/id_rsa .
    - chmod 0400 ./id_rsa
    - scp -o StrictHostKeyChecking=no -i ./id_rsa bin/update.sh ${REMOTE_USER}@${REMOTE_HOST}:~
    - ssh -o StrictHostKeyChecking=no -i ./id_rsa ${REMOTE_USER}@${REMOTE_HOST} ./update.sh
    - rm -f ./id_rsa
