# image: "ubuntu:18.04"

# before_script:
#   - echo hello from gitlab ci
#   - echo here is the next line
#   - echo remote host is $REMOTE_HOST and the sky is blue

# foo:
#   script:
#     - echo hello from foo
#     - echo foo line 2

deploy:
  only:
    refs:
      - migrate-ci-to-gitlab # TODO change to prod
  script:
    - |
    echo AWS_ACCESS_KEY_ID=${{  secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY  }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} aws s3 cp s3://motuz-test/cicd/id_rsa .
    echo chmod 0400 ./id_rsa
    echo scp -o StrictHostKeyChecking=no -i ./id_rsa bin/update.sh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~
    echo ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} ./update.sh
    echo rm -f ./id_rsa
