deploy:
  only:
    refs:
      - migrate-ci-to-gitlab # TODO change to prod
  script:
    - echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION aws s3 cp s3://motuz-test/cicd/id_rsa .
    - echo chmod 0400 ./id_rsa
    - echo scp -o StrictHostKeyChecking=no -i ./id_rsa bin/update.sh ${REMOTE_USER}@${REMOTE_HOST}:~
    - echo ssh -o StrictHostKeyChecking=no -i ./id_rsa ${REMOTE_USER}@${REMOTE_HOST} ./update.sh
    - echo rm -f ./id_rsa
