version: '3.4'

# See the fully generated file using
# docker-compose config


x-variables:
    - &database-environment
        MOTUZ_DATABASE_PROTOCOL:    # from ./.env
        MOTUZ_DATABASE_USER:        # from ./.env
        MOTUZ_DATABASE_HOST:        # from ./.env
        MOTUZ_DATABASE_NAME:        # from ./.env
        MOTUZ_DATABASE_REQUIRE_SSL: # from ./.env
    - &smtp-environment
        MOTUZ_SMTP_SERVER:          # from ./.env
        MOTUZ_SMTP_USER:            # from ./.env
        MOTUZ_SMTP_REQUIRE_SSL:     # from ./.env
    - &shared-volumes
        volumes:
            # Using system users for authentication
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /etc/shadow:/etc/shadow:ro

            # Authentication
            # passwd/group should be mounted into any container
            # needing to share the user/group IDs
            # This is the setup for Fred Hutch where we use Ubuntu; for Red Hat you would
            # want to use SSSD.
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /etc/krb5.conf:/etc/krb5.conf
            - /etc/pam.d:/etc/pam.d

            # Authentication cannot mount individual files, because the mapping is
            # based on the inode
            - /etc:/etc:ro


secrets:
    MOTUZ_DATABASE_PASSWORD:
        file: /docker/secrets/MOTUZ_DATABASE_PASSWORD
    MOTUZ_FLASK_SECRET_KEY:
        file: /docker/secrets/MOTUZ_FLASK_SECRET_KEY
    MOTUZ_SMTP_PASSWORD:
        file: /docker/secrets/MOTUZ_SMTP_PASSWORD


services:
    nginx:
        container_name: motuz_nginx
        image: fredhutch/motuz_nginx
        network_mode: host
        volumes:
            - /root/certs:/certs/:ro
        ports:
            - 443:443
            - 80:80


    app:
        container_name: motuz_app
        image: fredhutch/motuz_app
        network_mode: host
        <<: *shared-volumes
        ports:
            - 5000:5000
        environment:
            <<: *database-environment
        secrets:
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_FLASK_SECRET_KEY


    celery:
        container_name: motuz_celery
        image: fredhutch/motuz_celery
        network_mode: host
        <<: *shared-volumes
        environment:
            <<: *database-environment
            <<: *smtp-environment
        secrets:
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_FLASK_SECRET_KEY
            - MOTUZ_SMTP_PASSWORD
        depends_on:
            - app # Build dependency


    rabbitmq:
        container_name: motuz_rabbitmq
        network_mode: host
        image: rabbitmq:3.7.16
        ports:
            - 5672:5672
            - 15672:15672


    database:
        container_name: motuz_database
        network_mode: host
        image: postgres:11.3
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432


    database_init:
        container_name: motuz_database_init
        image: fredhutch/motuz_database_init
        network_mode: host
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data
        environment:
            <<: *database-environment
        secrets:
            - MOTUZ_DATABASE_PASSWORD
