version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - .:/code
        ports:
            - "80:80"
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - .:/code
        ports:
            - "5000:5000"
    celery:
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A api.tasks worker -l info
        volumes:
            - .:/code
        hostname: 0.0.0.0
    rabbitmq:
        network_mode: host
        image: "rabbitmq:3-management"
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 5672
        hostname: 0.0.0.0
