version: '3.1'

services:

    motuz_nginx:
        container_name: motuz_nginx
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - .:/code
            - /tmp
            - /root/certs:/certs/:ro
        ports:
            - 443:443
            - 80:80
        logging:
            driver: syslog


    motuz_app:
        container_name: motuz_app
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - .:/code

            # Authentication
            # passwd/group should be mounted into any container
            # needing to share the user/group IDs
            # This is the setup for Fred Hutch where we use Ubuntu; for Red Hat you would
            # want to use SSSD.
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /etc/krb5.conf:/etc/krb5.conf
            - /etc/pam.d:/etc/pam.d

            # Authentication cannot mount individual files, because the mapping is
            # based on the inode
            - /etc:/etc:ro

            - /home:/home:shared
            - /tmp

            # These mounts are specific to Fred Hutch:
            - /efs/:/efs/
            - /fh/economy:/fh/economy:shared
            - /fh/fast:/fh/fast:shared
            - /fh/secure:/fh/secure:shared
            - /fh/scratch/:/fh/scratch/
            - /fh/silver:/fh/silver:shared

            - /shared:/shared:shared

        secrets:
            - MOTUZ_DATABASE_USER
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_DATABASE_NAME
            - MOTUZ_FLASK_SECRET_KEY

        ports:
            - 5000:5000
            - 5001:5001


    motuz_celery:
        container_name: motuz_celery
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        volumes:
            - .:/code

            # # Authentication
            # # passwd/group should be mounted into any container
            # # needing to share the user/group IDs
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /etc/krb5.conf:/etc/krb5.conf
            - /etc/pam.d:/etc/pam.d

            # # Authentication cannot mount individual files, because the mapping is
            # # based on the inode
            - /etc:/etc:ro

            - /home:/home:shared


            # Fred Hutch speciic mounts
            - /efs/:/efs/
            - /fh/economy:/fh/economy:shared
            - /fh/fast:/fh/fast:shared
            - /fh/secure:/fh/secure:shared
            - /fh/scratch/:/fh/scratch/
            - /fh/silver:/fh/silver:shared
            - /shared:/shared:shared


        secrets:
            - MOTUZ_DATABASE_USER
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_DATABASE_NAME
            - MOTUZ_FLASK_SECRET_KEY


        hostname: 0.0.0.0
        depends_on:
            - motuz_app


    motuz_rabbitmq:
        container_name: motuz_rabbitmq
        network_mode: host
        image: rabbitmq:3.7.16
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 5672
        hostname: 0.0.0.0


    motuz_database:
        container_name: motuz_database
        network_mode: host
        environment:
          POSTGRES_PASSWORD:
        image: postgres:11.3
        ports:
            - 5432:5432
        hostname: 0.0.0.0
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data


    motuz_database_init:
        container_name: motuz_database_init
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/database_init/Dockerfile
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data
        secrets:
            - MOTUZ_DATABASE_USER
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_DATABASE_NAME
        hostname: 0.0.0.0



secrets:
    MOTUZ_DATABASE_USER:
        file: /docker/secrets/MOTUZ_DATABASE_USER
    MOTUZ_DATABASE_PASSWORD:
        file: /docker/secrets/MOTUZ_DATABASE_PASSWORD
    MOTUZ_DATABASE_NAME:
        file: /docker/secrets/MOTUZ_DATABASE_NAME
    MOTUZ_FLASK_SECRET_KEY:
        file: /docker/secrets/MOTUZ_FLASK_SECRET_KEY
