version: '3.1'

services:

    nginx:
        container_name: motuz_nginx
        image: fredhutch/motuz_nginx
        network_mode: host
        volumes:
            - /root/certs:/certs/:ro
        ports:
            - 443:443
            - 80:80

    app:
        container_name: motuz_app
        image: fredhutch/motuz_app
        network_mode: host
        volumes:
            # Authentication
            # passwd/group should be mounted into any container
            # needing to share the user/group IDs
            # This is the setup for Fred Hutch where we use Ubuntu; for Red Hat you would
            # want to use SSSD.
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /etc/krb5.conf:/etc/krb5.conf
            - /etc/pam.d:/etc/pam.d

            # Authentication cannot mount individual files, because the mapping is
            # based on the inode
            - /etc:/etc:ro

            - /home:/home:shared
            - /tmp

            # These mounts are specific to Fred Hutch:
            - /efs/:/efs/
            - /fh/economy:/fh/economy:shared
            - /fh/fast:/fh/fast:shared
            - /fh/secure:/fh/secure:shared
            - /fh/scratch/:/fh/scratch/
            - /fh/silver:/fh/silver:shared
            - /shared:/shared:shared
        ports:
            - 5000:5000

        environment:
            - MOTUZ_DATABASE_PROTOCOL    # from ./.env
            - MOTUZ_DATABASE_USER        # from ./.env
            - MOTUZ_DATABASE_HOST        # from ./.env
            - MOTUZ_DATABASE_NAME        # from ./.env
            - MOTUZ_DATABASE_REQUIRE_SSL # from ./.env
        secrets:
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_FLASK_SECRET_KEY



    celery:
        container_name: motuz_celery
        network_mode: host
        build:
            context: .
            dockerfile: ./prod/docker/celery/Dockerfile
        volumes:
            - .:/code

            # # Authentication
            # # passwd/group should be mounted into any container
            # # needing to share the user/group IDs
            - /var/run/nscd/socket:/var/run/nscd/socket
            - /etc/krb5.conf:/etc/krb5.conf
            - /etc/pam.d:/etc/pam.d

            # # Authentication cannot mount individual files, because the mapping is
            # # based on the inode
            - /etc:/etc:ro

            - /home:/home:shared


            # Fred Hutch speciic mounts
            - /efs/:/efs/
            - /fh/economy:/fh/economy:shared
            - /fh/fast:/fh/fast:shared
            - /fh/secure:/fh/secure:shared
            - /fh/scratch/:/fh/scratch/
            - /fh/silver:/fh/silver:shared
            - /shared:/shared:shared

        environment:
            - MOTUZ_DATABASE_PROTOCOL    # from ./.env
            - MOTUZ_DATABASE_USER        # from ./.env
            - MOTUZ_DATABASE_HOST        # from ./.env
            - MOTUZ_DATABASE_NAME        # from ./.env
            - MOTUZ_DATABASE_REQUIRE_SSL # from ./.env

            - MOTUZ_SMTP_SERVER          # from ./.env
            - MOTUZ_SMTP_USER            # from ./.env
            - MOTUZ_SMTP_REQUIRE_SSL     # from ./.env
        secrets:
            - MOTUZ_DATABASE_PASSWORD
            - MOTUZ_FLASK_SECRET_KEY
            - MOTUZ_SMTP_PASSWORD

        hostname: 0.0.0.0
        depends_on:
            - app


    rabbitmq:
        container_name: motuz_rabbitmq
        network_mode: host
        image: rabbitmq:3.7.16
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 5672
        hostname: 0.0.0.0


    database:
        container_name: motuz_database
        network_mode: host
        image: postgres:11.3
        ports:
            - 5432:5432
        hostname: 0.0.0.0
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data


    database_init:
        container_name: motuz_database_init
        network_mode: host
        build:
            context: .
            dockerfile: ./prod/docker/database_init/Dockerfile
        volumes:
            - /docker/volumes/postgres:/var/lib/postgresql/data
        environment:
            - MOTUZ_DATABASE_PROTOCOL    # from ./.env
            - MOTUZ_DATABASE_USER        # from ./.env
            - MOTUZ_DATABASE_HOST        # from ./.env
            - MOTUZ_DATABASE_NAME        # from ./.env
            - MOTUZ_DATABASE_REQUIRE_SSL # from ./.env
        secrets:
            - MOTUZ_DATABASE_PASSWORD
        hostname: 0.0.0.0



secrets:
    MOTUZ_DATABASE_PASSWORD:
        file: /docker/secrets/MOTUZ_DATABASE_PASSWORD
    MOTUZ_FLASK_SECRET_KEY:
        file: /docker/secrets/MOTUZ_FLASK_SECRET_KEY
    MOTUZ_SMTP_PASSWORD:
        file: /docker/secrets/MOTUZ_SMTP_PASSWORD
