"""empty message

Revision ID: 09ba60b91034
Revises: 8fdf8259859b
Create Date: 2019-05-25 17:53:22.272118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ba60b91034'
down_revision = '8fdf8259859b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_job', 'description')
    # ### end Alembic commands ###
