"""empty message

Revision ID: 4a40191fc890
Revises: a5879be2fd07
Create Date: 2019-06-10 23:06:00.575947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a40191fc890'
down_revision = 'a5879be2fd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('progress_current', sa.Integer(), nullable=True))
    op.add_column('copy_job', sa.Column('progress_error', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('progress_state', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('progress_total', sa.Integer(), nullable=True))
    op.add_column('copy_job', sa.Column('updated_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('copy_job') as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('completed_at', sa.DATETIME(), nullable=True))
    op.add_column('copy_job', sa.Column('status', sa.VARCHAR(), nullable=True))
    with op.batch_alter_table('copy_job') as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('progress_total')
        batch_op.drop_column('progress_state')
        batch_op.drop_column('progress_error')
        batch_op.drop_column('progress_current')
    # ### end Alembic commands ###
