"""empty message

Revision ID: 0d4810515c25
Revises: 80ce05699ec9
Create Date: 2019-07-03 17:22:19.598536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4810515c25'
down_revision = '80ce05699ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('azure_account', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('azure_key', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('gcp_bucket_acl', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('gcp_client_id', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('gcp_object_acl', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('gcp_project_number', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('gcp_service_account_credentials', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('s3_endpoint', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('s3_v2_auth', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('swift_auth', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('swift_key', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('swift_tenant', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('swift_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'swift_user')
    op.drop_column('cloud_connection', 'swift_tenant')
    op.drop_column('cloud_connection', 'swift_key')
    op.drop_column('cloud_connection', 'swift_auth')
    op.drop_column('cloud_connection', 's3_v2_auth')
    op.drop_column('cloud_connection', 's3_endpoint')
    op.drop_column('cloud_connection', 'gcp_service_account_credentials')
    op.drop_column('cloud_connection', 'gcp_project_number')
    op.drop_column('cloud_connection', 'gcp_object_acl')
    op.drop_column('cloud_connection', 'gcp_client_id')
    op.drop_column('cloud_connection', 'gcp_bucket_acl')
    op.drop_column('cloud_connection', 'azure_key')
    op.drop_column('cloud_connection', 'azure_account')
    # ### end Alembic commands ###
