"""empty message

Revision ID: 62d05dee22b9
Revises: dbdcb592b079
Create Date: 2019-12-07 15:22:37.801671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d05dee22b9'
down_revision = 'dbdcb592b079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('sftp_host', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('sftp_pass', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('sftp_port', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('sftp_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'sftp_user')
    op.drop_column('cloud_connection', 'sftp_port')
    op.drop_column('cloud_connection', 'sftp_pass')
    op.drop_column('cloud_connection', 'sftp_host')
    # ### end Alembic commands ###
