"""empty message

Revision ID: ea775e9f7dc2
Revises: 234567debc78
Create Date: 2019-06-27 19:26:54.056112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea775e9f7dc2'
down_revision = '234567debc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('src_cloud_id', sa.Integer(), nullable=True),
    sa.Column('src_resource', sa.String(), nullable=True),
    sa.Column('dst_cloud_id', sa.Integer(), nullable=True),
    sa.Column('dst_path', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('progress_state', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dst_cloud_id'], ['cloud_connection.id'], ),
    sa.ForeignKeyConstraint(['src_cloud_id'], ['cloud_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copy_job')
    # ### end Alembic commands ###
