"""empty message

Revision ID: be6b24ca2267
Revises: f67d1772b513
Create Date: 2019-12-14 12:02:25.974092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6b24ca2267'
down_revision = 'f67d1772b513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('azure_sas_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'azure_sas_url')
    # ### end Alembic commands ###
