"""empty message

Revision ID: dbdcb592b079
Revises: 9ec4e6d9381e
Create Date: 2019-12-03 08:46:17.920790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdcb592b079'
down_revision = '9ec4e6d9381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('copy_links', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_job', 'copy_links')
    # ### end Alembic commands ###
