"""empty message

Revision ID: 1035b06e75e0
Revises: 749eb9900744
Create Date: 2019-12-14 14:50:46.892949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1035b06e75e0'
down_revision = '749eb9900744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('webdav_pass', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('webdav_url', sa.String(), nullable=True))
    op.add_column('cloud_connection', sa.Column('webdav_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'webdav_user')
    op.drop_column('cloud_connection', 'webdav_url')
    op.drop_column('cloud_connection', 'webdav_pass')
    # ### end Alembic commands ###
