"""empty message

Revision ID: 847966058a76
Revises: 0d4810515c25
Create Date: 2019-07-05 19:02:16.238976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847966058a76'
down_revision = '0d4810515c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('progress_execution_time', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_job', 'progress_execution_time')
    # ### end Alembic commands ###
