"""empty message

Revision ID: 36e7b008822b
Revises: ec9caac1c4c3
Create Date: 2020-03-01 18:30:31.573209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e7b008822b'
down_revision = 'ec9caac1c4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashsum_job', sa.Column('dst_cloud_id', sa.Integer(), nullable=True))
    op.add_column('hashsum_job', sa.Column('dst_resource_path', sa.String(), nullable=True))
    op.create_foreign_key(None, 'hashsum_job', 'cloud_connection', ['dst_cloud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hashsum_job', type_='foreignkey')
    op.drop_column('hashsum_job', 'dst_resource_path')
    op.drop_column('hashsum_job', 'dst_cloud_id')
    # ### end Alembic commands ###
