"""empty message

Revision ID: ec9caac1c4c3
Revises: 11d077f3627a
Create Date: 2020-03-01 18:26:53.465257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9caac1c4c3'
down_revision = '11d077f3627a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashsum_job', sa.Column('src_cloud_id', sa.Integer(), nullable=True))
    op.add_column('hashsum_job', sa.Column('src_resource_path', sa.String(), nullable=True))
    op.drop_constraint('hashsum_job_cloud_id_fkey', 'hashsum_job', type_='foreignkey')
    op.create_foreign_key(None, 'hashsum_job', 'cloud_connection', ['src_cloud_id'], ['id'])
    op.drop_column('hashsum_job', 'resource_path')
    op.drop_column('hashsum_job', 'cloud_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashsum_job', sa.Column('cloud_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hashsum_job', sa.Column('resource_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hashsum_job', type_='foreignkey')
    op.create_foreign_key('hashsum_job_cloud_id_fkey', 'hashsum_job', 'cloud_connection', ['cloud_id'], ['id'])
    op.drop_column('hashsum_job', 'src_resource_path')
    op.drop_column('hashsum_job', 'src_cloud_id')
    # ### end Alembic commands ###
