"""empty message

Revision ID: 1d453219803e
Revises: bb59b6777634
Create Date: 2020-10-07 20:02:58.166211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d453219803e'
down_revision = 'bb59b6777634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashsum_job', sa.Column('progress_dst_error', sa.String(), nullable=True))
    op.add_column('hashsum_job', sa.Column('progress_dst_tree', sa.String(), server_default='[]', nullable=True))
    op.add_column('hashsum_job', sa.Column('progress_src_error', sa.String(), nullable=True))
    op.add_column('hashsum_job', sa.Column('progress_src_tree', sa.String(), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashsum_job', 'progress_src_tree')
    op.drop_column('hashsum_job', 'progress_src_error')
    op.drop_column('hashsum_job', 'progress_dst_tree')
    op.drop_column('hashsum_job', 'progress_dst_error')
    # ### end Alembic commands ###
