"""empty message

Revision ID: 11d077f3627a
Revises: 0ed04a434168
Create Date: 2020-02-09 00:23:23.959564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d077f3627a'
down_revision = '0ed04a434168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashsum_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_id', sa.Integer(), nullable=True),
    sa.Column('resource_path', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('progress_state', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_error', sa.String(), nullable=True),
    sa.Column('progress_execution_time', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['cloud_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashsum_job')
    # ### end Alembic commands ###
