"""empty message

Revision ID: 0ed04a434168
Revises: 881811805554
Create Date: 2020-01-25 09:26:33.325988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed04a434168'
down_revision = '881811805554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('sftp_key_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'sftp_key_file')
    # ### end Alembic commands ###
