"""empty message

Revision ID: e9dc9c11604f
Revises: 0ed04a434168
Create Date: 2020-03-09 22:40:08.140747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dc9c11604f'
down_revision = '0ed04a434168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashsum_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_cloud_id', sa.Integer(), nullable=True),
    sa.Column('src_resource_path', sa.String(), nullable=True),
    sa.Column('dst_cloud_id', sa.Integer(), nullable=True),
    sa.Column('dst_resource_path', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('progress_state', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_error', sa.String(), nullable=True),
    sa.Column('progress_execution_time', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dst_cloud_id'], ['cloud_connection.id'], ),
    sa.ForeignKeyConstraint(['src_cloud_id'], ['cloud_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashsum_job')
    # ### end Alembic commands ###
