"""empty message

Revision ID: cb321d9a4a6c
Revises: 51633c8a4305
Create Date: 2022-06-08 18:08:30.379479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb321d9a4a6c'
down_revision = '51633c8a4305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_copy_job_owner'), 'copy_job', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copy_job_owner'), table_name='copy_job')
    # ### end Alembic commands ###
