"""add kms_encryption_key_arn

Revision ID: 42a4b7401b23
Revises: cb321d9a4a6c
Create Date: 2025-06-07 20:32:06.589201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a4b7401b23'
down_revision = 'cb321d9a4a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_connection', sa.Column('kms_encryption_key_arn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_connection', 'kms_encryption_key_arn')
    # ### end Alembic commands ###
