"""empty message

Revision ID: 8fdf8259859b
Revises: a10a2986aaec
Create Date: 2019-05-25 16:31:25.061908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdf8259859b'
down_revision = 'a10a2986aaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_job', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('copy_job', sa.Column('dst_cloud', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('dst_path', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('src_cloud', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('src_resource', sa.String(), nullable=True))
    op.add_column('copy_job', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_job', 'status')
    op.drop_column('copy_job', 'src_resource')
    op.drop_column('copy_job', 'src_cloud')
    op.drop_column('copy_job', 'owner')
    op.drop_column('copy_job', 'dst_path')
    op.drop_column('copy_job', 'dst_cloud')
    op.drop_column('copy_job', 'completed_at')
    # ### end Alembic commands ###
