class HTTP_EXCEPTION(Exception):
    code = -1

    def __init__(self, payload={}):
        self.payload = payload


class HTTP_4XX_EXCEPTION(HTTP_EXCEPTION):
    pass

class HTTP_5XX_EXCEPTION(HTTP_EXCEPTION):
    pass


# 4xx Codes

class HTTP_400_BAD_REQUEST(HTTP_4XX_EXCEPTION):
    code = 400

class HTTP_401_UNAUTHORIZED(HTTP_4XX_EXCEPTION):
    code = 401

class HTTP_402_PAYMENT_REQUIRED(HTTP_4XX_EXCEPTION):
    code = 402

class HTTP_403_FORBIDDEN(HTTP_4XX_EXCEPTION):
    code = 403

class HTTP_404_NOT_FOUND(HTTP_4XX_EXCEPTION):
    code = 404

class HTTP_405_METHOD_NOT_ALLOWED(HTTP_4XX_EXCEPTION):
    code = 405


# 5xx Codes


class HTTP_500_INTERNAL_SERVER_ERROR(HTTP_5XX_EXCEPTION):
    code = 500

class HTTP_501_NOT_IMPLEMENTED(HTTP_5XX_EXCEPTION):
    code = 501

class HTTP_502_BAD_GATEWAY(HTTP_5XX_EXCEPTION):
    code = 502

class HTTP_503_SERVICE_UNAVAILABLE(HTTP_5XX_EXCEPTION):
    code = 503

class HTTP_504_GATEWAY_TIMEOUT(HTTP_5XX_EXCEPTION):
    code = 504

class HTTP_505_HTTP_VERSION_NOT_SUPPORTED(HTTP_5XX_EXCEPTION):
    code = 505

class HTTP_507_INSUFFICIENT_STORAGE(HTTP_5XX_EXCEPTION):
    code = 507

class HTTP_511_NETWORK_AUTHENTICATION_REQUIRED(HTTP_5XX_EXCEPTION):
    code = 511
