name: CI

on:
  push:
    branches:
      - prod

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: |
        AWS_ACCESS_KEY_ID=${{  secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY  }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} aws s3 cp s3://motuz-test/cicd/id_rsa .
        chmod 0400 ./id_rsa
        scp -o StrictHostKeyChecking=no -i ./id_rsa bin/update.sh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~
        ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} ./update.sh
        rm -f ./id_rsa

